Update action.yaml

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -121,19 +121,34 @@ runs:
             echo "ERROR: project_name is required when generate_sbom is true!"
             exit 1
           fi
-
+        
+          # Sanitise project name (keep spaces)
+          SAFE_PROJECT_NAME="$(echo "$ACCUKNOX_PROJECT_NAME" | sed 's/[^a-zA-Z0-9 ._-]/_/g')"
+        
+          if [ -z "$SAFE_PROJECT_NAME" ]; then
+            echo "ERROR: project_name is empty after sanitization"
+            exit 1
+          fi
+        
           echo "Running AccuKnox SBOM generation:"
-          echo "./accuknox-aspm-scanner scan $SOFT_FAIL_ARG $KEEP_RESULTS_ARG $PROJECT_NAME_ARG container --command \"$CMD\" --container-mode --generate-sbom"
-
+          echo "./accuknox-aspm-scanner scan \
+        $SOFT_FAIL_ARG \
+        $KEEP_RESULTS_ARG \
+        --project-name \"$SAFE_PROJECT_NAME\" \
+        container \
+        --command \"$CMD\" \
+        --container-mode \
+        --generate-sbom"
+        
           ./accuknox-aspm-scanner scan \
             $SOFT_FAIL_ARG \
             $KEEP_RESULTS_ARG \
-            --project-name "$ACCUKNOX_PROJECT_NAME" \
+            --project-name "$SAFE_PROJECT_NAME" \
             container \
             --command "$CMD" \
             --container-mode \
             --generate-sbom
-
+        
           mv results.json results-sbom.json
         fi
         
